export const foundryGlobals = {
  Folder: "readonly",
  ActiveEffect: "readonly",
  ProseMirror: "readonly",
  Actor: "readonly",
  Item: "readonly",
  canvas: "readonly",
  fromUuidSync: "readonly",
  CONST: "readonly",
  cthulhuTech: "readonly",
  Hooks: "readonly",
  ChatMessage: "readonly",
  globalThis: "readonly",
  ui: "readonly",
  fromUuid: "readonly",
  Handlebars: "readonly",
  CONFIG: "readonly",
  foundry: "readonly",
  game: "readonly",
};
