on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*-beta' # Push events to matching v*-beta, i.e. v1.0-beta, v20.15.10-beta

name: Upload Release Asset

jobs:
  build:
    permissions: write-all
    name: Upload Release Asset
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup NodeJS 22
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install node modules
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Extract Version From Tag
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Get Module ID
        id: moduleID
        uses: notiz-dev/github-action-json-property@release
        with:
          path: './dist/module.json'
          prop_path: 'id'

      - name: Get mininum
        id: minimum
        uses: notiz-dev/github-action-json-property@release
        with:
          path: './dist/module.json'
          prop_path: 'compatibility.minimum'

      - name: Get verified
        id: verified
        uses: notiz-dev/github-action-json-property@release
        with:
          path: './dist/module.json'
          prop_path: 'compatibility.verified'

      - name: Modify Module Manifest With Release-Specific Values
        id: sub_manifest_link_version
        uses: microsoft/variable-substitution@v1
        with:
          files: './dist/module.json'
        env:
          version: ${{steps.get_version.outputs.version-without-v}}
          url: https://github.com/${{github.repository}}
          manifest: https://github.com/${{github.repository}}/releases/latest/download/module.json
          download: https://github.com/${{github.repository}}/releases/download/${{steps.get_version.outputs.version}}/${{steps.moduleID.outputs.prop}}.zip
          readme: https://github.com/${{github.repository}}/blob/${{steps.get_version.outputs.version}}/README.md
          changelog: https://github.com/${{github.repository}}/blob/${{steps.get_version.outputs.version}}/CHANGELOG.md
          bugs: https://github.com/${{github.repository}}/issues

      - name: Create ZIP
        run: |
          cd dist
          zip -r ../${{steps.moduleID.outputs.prop}}.zip *

      - name: Create Release
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref }}
          name: Release ${{steps.get_version.outputs.version}}
          artifacts: './dist/module.json, ${{steps.moduleID.outputs.prop}}.zip'
          allowUpdates: true
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
